import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./ui/components/sidebar/sidebar";
import Topbar from "./ui/components/topbar/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FBFFFB]`}
      >
        <div className="flex">
      <Sidebar />
      <div className="flex-1 ">
        <Topbar />
        <main className="mt-[65px]  ml-0 lg:ml-20">{children}</main>
      </div>
    </div>
      </body>
    </html>
  );
}
